### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [davidlky/Mapper#9]
Hi @davidlky I would like to design a logo for your project. I am a graphic artist . If you are interested i will start my design asap. Thanks and regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by davidlky** [comment]
@Tobaloidee Thanks you so much for the offer and your work is amazing! Sadly, I'm still trying to figure out what the project will be just yet so perhaps I'll reach out when I get a better idea.

**Comment by Tobaloidee** [comment]
Just reach me out and i'll be here 👍
